[package]
name = "intellij-loong-native-helper"
version = "0.1.0"
edition = "2018"

[dependencies.ra_ap_proc_macro_srv]
git = "https://github.com/rust-analyzer/rust-analyzer"
package = "proc-macro-srv"
rev = "6cb0746f8223cc674f1a4496f80b21d7cf231799"

[target."cfg(windows)".dependencies.winapi]
version = "*"
features = ["winerror", "processthreadsapi", "psapi"]

[profile.release]
lto = "fat"
codegen-units = 1
debug = false
